services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
    networks:
      - auth_network
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: redis
    environment:
      REDIS_DATABASES: ${REDIS_DB}
    networks:
      - auth_network
    volumes:
      - redis_data:/data

volumes:
  pg_data:
  redis_data:

networks:
  auth_network:
    external: true
