services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      POSTGRES_USER: ${POSTGRES_DB_USER}
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASS}
    networks:
      - auth_network
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  auth_network:
    external: true
