"""addd unique

Revision ID: 0dde5cdd1554
Revises: eb8ee6715918
Create Date: 2025-07-27 01:09:38.243093

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dde5cdd1554'
down_revision: Union[str, Sequence[str], None] = 'eb8ee6715918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'vk_users', ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vk_users', type_='unique')
    # ### end Alembic commands ###
