"""add field

Revision ID: 25313976250b
Revises: e709cc430018
Create Date: 2025-07-27 01:38:16.493541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25313976250b'
down_revision: Union[str, Sequence[str], None] = 'e709cc430018'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('yandex_users', sa.Column('is_avatar_empty', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('yandex_users', 'is_avatar_empty')
    # ### end Alembic commands ###
