"""new model

Revision ID: 34cd7b6c533c
Revises: 5e5d1755077a
Create Date: 2025-07-27 02:26:09.200324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34cd7b6c533c'
down_revision: Union[str, Sequence[str], None] = '5e5d1755077a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=True),
    sa.Column('yandex_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['yandex_user_id'], ['yandex_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_users_id'), 'sessions_users', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_users_vk_user_id'), 'sessions_users', ['vk_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_users_yandex_user_id'), 'sessions_users', ['yandex_user_id'], unique=False)
    op.drop_index(op.f('ix_sessions_yandex_users_id'), table_name='sessions_yandex_users')
    op.drop_index(op.f('ix_sessions_yandex_users_yandex_user_id'), table_name='sessions_yandex_users')
    op.drop_table('sessions_yandex_users')
    op.drop_index(op.f('ix_sessions_vk_users_id'), table_name='sessions_vk_users')
    op.drop_index(op.f('ix_sessions_vk_users_vk_user_id'), table_name='sessions_vk_users')
    op.drop_table('sessions_vk_users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_vk_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('vk_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], name=op.f('sessions_vk_users_vk_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_vk_users_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('sessions_vk_users_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sessions_vk_users_vk_user_id'), 'sessions_vk_users', ['vk_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_vk_users_id'), 'sessions_vk_users', ['id'], unique=False)
    op.create_table('sessions_yandex_users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('yandex_user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['yandex_user_id'], ['yandex_users.id'], name=op.f('sessions_yandex_users_yandex_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sessions_yandex_users_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('sessions_yandex_users_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_sessions_yandex_users_yandex_user_id'), 'sessions_yandex_users', ['yandex_user_id'], unique=False)
    op.create_index(op.f('ix_sessions_yandex_users_id'), 'sessions_yandex_users', ['id'], unique=False)
    op.drop_index(op.f('ix_sessions_users_yandex_user_id'), table_name='sessions_users')
    op.drop_index(op.f('ix_sessions_users_vk_user_id'), table_name='sessions_users')
    op.drop_index(op.f('ix_sessions_users_id'), table_name='sessions_users')
    op.drop_table('sessions_users')
    # ### end Alembic commands ###
