"""session models

Revision ID: 5e5d1755077a
Revises: bd4140231d89
Create Date: 2025-07-27 02:12:01.452275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5d1755077a'
down_revision: Union[str, Sequence[str], None] = 'bd4140231d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions_vk_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('vk_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vk_user_id'], ['vk_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_vk_users_id'), 'sessions_vk_users', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_vk_users_vk_user_id'), 'sessions_vk_users', ['vk_user_id'], unique=False)
    op.create_table('sessions_yandex_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=64), nullable=False),
    sa.Column('yandex_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['yandex_user_id'], ['yandex_users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_index(op.f('ix_sessions_yandex_users_id'), 'sessions_yandex_users', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_yandex_users_yandex_user_id'), 'sessions_yandex_users', ['yandex_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_yandex_users_yandex_user_id'), table_name='sessions_yandex_users')
    op.drop_index(op.f('ix_sessions_yandex_users_id'), table_name='sessions_yandex_users')
    op.drop_table('sessions_yandex_users')
    op.drop_index(op.f('ix_sessions_vk_users_vk_user_id'), table_name='sessions_vk_users')
    op.drop_index(op.f('ix_sessions_vk_users_id'), table_name='sessions_vk_users')
    op.drop_table('sessions_vk_users')
    # ### end Alembic commands ###
