"""change vk mode rename field

Revision ID: bd4140231d89
Revises: 25313976250b
Create Date: 2025-07-27 01:42:39.944626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd4140231d89'
down_revision: Union[str, Sequence[str], None] = '25313976250b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_users', sa.Column('vk_id', sa.String(), nullable=False))
    op.drop_constraint(op.f('vk_users_user_id_key'), 'vk_users', type_='unique')
    op.create_unique_constraint(None, 'vk_users', ['vk_id'])
    op.drop_column('vk_users', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vk_users', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'vk_users', type_='unique')
    op.create_unique_constraint(op.f('vk_users_user_id_key'), 'vk_users', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('vk_users', 'vk_id')
    # ### end Alembic commands ###
