"""change fields

Revision ID: c86e2c5df9dc
Revises: 32269aa2755c
Create Date: 2025-07-27 01:01:25.598665

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c86e2c5df9dc'
down_revision: Union[str, Sequence[str], None] = '32269aa2755c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vk_users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vk_users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vk_users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vk_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vk_users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vk_users', 'avatar',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vk_users', 'phone',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vk_users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vk_users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
