"""add yandex user models

Revision ID: e709cc430018
Revises: 0dde5cdd1554
Create Date: 2025-07-27 01:28:17.468251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e709cc430018'
down_revision: Union[str, Sequence[str], None] = '0dde5cdd1554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('yandex_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('yandex_id', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('client_id', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('real_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('sex', sa.String(), nullable=True),
    sa.Column('default_email', sa.String(), nullable=True),
    sa.Column('emails', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('birthday', sa.String(), nullable=True),
    sa.Column('default_avatar_id', sa.String(), nullable=True),
    sa.Column('default_phone', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('psuid', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('yandex_id')
    )
    op.create_index(op.f('ix_yandex_users_id'), 'yandex_users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_yandex_users_id'), table_name='yandex_users')
    op.drop_table('yandex_users')
    # ### end Alembic commands ###
